module.exports = {
    name: "fact",
    description: "Obtenir un fait aléatoire.",
    run: async (message, args, command, client) => {
        if (message.author.bot) {
            return;
        }

        // Liste de 30 faits aléatoires
        const facts = [
            "Les fourmis peuvent soulever jusqu'à 50 fois leur propre poids.",
            "L'océan Atlantique est plus grand que toute la surface terrestre.",
            "Le miel ne se gâte jamais. Des pots de miel vieux de milliers d'années ont été retrouvés dans des tombes égyptiennes.",
            "Les dauphins dorment avec un œil ouvert.",
            "La planète Mars a des tempêtes de poussière géantes qui peuvent obscurcir toute la planète pendant des mois.",
            "L'abeille mâle n'a pas de dard.",
            "Le rire est un langage universel compris par toutes les cultures.",
            "Le caméléon peut tourner ses yeux indépendamment l'un de l'autre.",
            "Le plongeur olympique Tom Daley est également un tricot expert.",
            "La lune s'éloigne de la Terre d'environ 3,8 cm par an.",
            "Le poisson-clown et l'anémone de mer ont une relation symbiotique.",
            "La Grande Muraille de Chine a été construite sur plusieurs dynasties pendant des siècles.",
            "Un escargot peut dormir jusqu'à 3 ans.",
            "Le corbeau est l'un des oiseaux les plus intelligents.",
            "Le miel est le seul aliment qui ne se gâte jamais.",
            "Il y a plus d'étoiles dans l'univers observable que de grains de sable sur toutes les plages de la Terre.",
            "Les phoques dorment souvent dans l'eau.",
            "Les rennes sont les seuls cervidés où les deux sexes ont des bois.",
            "Le blue-jean a été inventé par Levi Strauss en 1873.",
            "Le Titanic a frappé un iceberg le 14 avril 1912 et a coulé.",
            "Un groupe de kangourous est appelé une 'troupe'.",
            "Le cerveau humain a la capacité de stocker plus d'informations que l'ensemble de l'Internet.",
            "Les fourmis communiquent en utilisant des produits chimiques appelés phéromones.",
            "Un groupe de lions est appelé une 'fierté'.",
            "L'ornithorynque est un mammifère qui pond des œufs.",
            "L'œil d'une autruche est plus grand que son cerveau.",
            "Il existe plus de 200 types de chauve-souris dans le monde.",
            "La Grande Barrière de corail est la plus grande structure vivante de la Terre.",
            "Les araignées ont un liquide pour garder leurs pattes propres et collantes.",
            "Un groupe de lapins est appelé une 'fluffle'.",
			"Les fourmis peuvent soulever jusqu'à 50 fois leur propre poids.",
			"L'océan Atlantique est plus grand que toute la surface terrestre.",
			"Le miel ne se gâte jamais. Des pots de miel vieux de milliers d'années ont été retrouvés dans des tombes égyptiennes.",
			"Les dauphins dorment avec un œil ouvert.",
			"La planète Mars a des tempêtes de poussière géantes qui peuvent obscurcir toute la planète pendant des mois.",
			"L'abeille mâle n'a pas de dard.",
			"Le rire est un langage universel compris par toutes les cultures.",
			"Le caméléon peut tourner ses yeux indépendamment l'un de l'autre.",
			"Le plongeur olympique Tom Daley est également un tricot expert.",
			"La lune s'éloigne de la Terre d'environ 3,8 cm par an.",
			"Le poisson-clown et l'anémone de mer ont une relation symbiotique.",
			"La Grande Muraille de Chine a été construite sur plusieurs dynasties pendant des siècles.",
			"Un escargot peut dormir jusqu'à 3 ans.",
			"Le corbeau est l'un des oiseaux les plus intelligents.",
			"Le miel est le seul aliment qui ne se gâte jamais.",
			"Il y a plus d'étoiles dans l'univers observable que de grains de sable sur toutes les plages de la Terre.",
			"Les phoques dorment souvent dans l'eau.",
			"Les rennes sont les seuls cervidés où les deux sexes ont des bois.",
			"Le blue-jean a été inventé par Levi Strauss en 1873.",
			"Le Titanic a frappé un iceberg le 14 avril 1912 et a coulé.",
			"Un groupe de kangourous est appelé une 'troupe'.",
			"Le cerveau humain a la capacité de stocker plus d'informations que l'ensemble de l'Internet.",
			"Les fourmis communiquent en utilisant des produits chimiques appelés phéromones.",
			"Un groupe de lions est appelé une 'fierté'.",
			"L'ornithorynque est un mammifère qui pond des œufs.",
			"L'œil d'une autruche est plus grand que son cerveau.",
			"Il existe plus de 200 types de chauve-souris dans le monde.",
			"La Grande Barrière de corail est la plus grande structure vivante de la Terre.",
			"Les araignées ont un liquide pour garder leurs pattes propres et collantes.",
			"Un groupe de lapins est appelé une 'fluffle'.",
			"Le sang d'une mouffette est vert.",
			"Les girafes ont la même quantité de vertèbres cervicales que les humains.",
			"Les éléphants sont les seuls mammifères qui ne peuvent pas sauter.",
			"Le cri d'un canard ne fait pas écho.",
			"Les pieuvres ont trois cœurs.",
			"Il existe plus de combinaisons possibles d'échecs que d'atomes dans l'univers observable.",
			"Les dauphins ont des noms individuels pour se reconnaître.",
			"Un groupe de flamants roses est appelé une 'flamboyance'.",
			"Les oiseaux sont les descendants des dinosaures.",
			"Un jour sur Vénus est plus long qu'une année sur Vénus.",
			"La Terre était une seule terre supercontinentale appelée 'Pangée'.",
			"Les moustiques préfèrent piquer les personnes de type O.",
			"Le sommeil paradoxal est la phase du sommeil où nous rêvons le plus.",
			"Les lions sont les seuls grands félins qui vivent en groupes sociaux.",
			"L'eau est le seul composé qui existe naturellement sous forme liquide, solide et gazeuse sur Terre.",
			"L'arc-en-ciel est un cercle complet, mais la Terre bloque la moitié inférieure.",
			"L'abeille domestique peut voler jusqu'à 24 km/h.",
			"Les carottes étaient traditionnellement violettes avant d'être sélectionnées en orange.",
			"Le chameau stocke de la graisse dans sa bosse, pas de l'eau.",
			"Les seuls mammifères capables de voler sont les chauves-souris.",
			"Les pandas géants sont en réalité des carnivores, mais ils se nourrissent principalement de bambou.",
			"Les pieuvres n'ont pas de squelette, ce qui leur permet de se faufiler dans de petits espaces.",
			"Le colibri est le seul oiseau capable de voler en reculant.",
			"Un groupe de corbeaux est appelé un 'meurtre'.",
			"Les fourmis peuvent marcher vers l'arrière.",
			"La vache peut avoir des meilleures amies.",
			"Les dauphins ont des empreintes digitales uniques comme les humains.",
			"La Terre est la seule planète connue pour abriter la vie.",
			"Les hiboux ne peuvent pas bouger leurs yeux, ils doivent tourner la tête.",
			"Les escargots peuvent dormir jusqu'à 3 ans."
        ];

        // Choisissez un fait aléatoire dans la liste
        const randomFact = facts[Math.floor(Math.random() * facts.length)];

        // Envoyez le fait aléatoire dans le canal
        message.channel.send("Voici un fait aléatoire :");
        message.channel.send(randomFact);
    }
};
